version: '3.3'
services:
  db:
    image: mongo
    ports:
        - 27017:27017
    restart: always
    volumes:
        - ./data:/data
    container_name: mongo-db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/rabbitmq/lib:/var/lib/rabbitmq
        - ./data/rabbitmq/log:/var/log/rabbitmq
        - ./data/rabbitmq/etc:/etc/rabbitmq/
    environment:
        RABBITMQ_DEFAULT_USER: anle
        RABBITMQ_DEFAULT_PASS: anle
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
